# Generated by Django 4.0.4 on 2022-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=100)),
                ('urgent', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
