# Generated by Django 4.0.4 on 2022-05-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0002_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='urgent',
            field=models.IntegerField(default=0),
        ),
    ]
